// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmpt6OkwEfi_A60wld-1uCYjtpOMi0v1M',
    appId: '1:294661128960:web:38e3f77f48194d863ca9e5',
    messagingSenderId: '294661128960',
    projectId: 'mylandingpage-f232c',
    authDomain: 'mylandingpage-f232c.firebaseapp.com',
    storageBucket: 'mylandingpage-f232c.appspot.com',
    measurementId: 'G-0127K96J24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHnrAWnnFlBRLA6i8jnaBnT4Q7HitWrQY',
    appId: '1:294661128960:android:46393be3e717ce833ca9e5',
    messagingSenderId: '294661128960',
    projectId: 'mylandingpage-f232c',
    storageBucket: 'mylandingpage-f232c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjmjCuxjsddWPlMTBnW8Kr4FMDv98X21Q',
    appId: '1:294661128960:ios:5ca71830bf3b92413ca9e5',
    messagingSenderId: '294661128960',
    projectId: 'mylandingpage-f232c',
    storageBucket: 'mylandingpage-f232c.appspot.com',
    iosBundleId: 'com.example.landingPage',
  );
}
